### ISSUE TITLE
trpc v11

### ISSUE THREAD

**Issue by marc-on-github** [OrJDev/trpc-limiter#13]
warning " > @trpc-limiter/upstash@0.0.3" has incorrect peer dependency "@trpc/client@^10.0.0-proxy-beta.21".
warning " > @trpc-limiter/upstash@0.0.3" has incorrect peer dependency "@trpc/server@^10.0.0-proxy-beta.21".
warning "@trpc-limiter/upstash > @trpc-limiter/core@0.0.8" has incorrect peer dependency "@trpc/client@^10.0.0-proxy-beta.21".
warning "@trpc-limiter/upstash > @trpc-limiter/core@0.0.8" has incorrect peer dependency "@trpc/server@^10.0.0-proxy-beta.21".

Is an update planned?

**Comment by fzn0x** [comment]
Looks like this library unmaintained

**Comment by periakteon** [comment]
same issue

**Comment by OrJDev** [comment]
Im going to release a new version today / tomorrow, im about to finish it but i had to quit in the middle for the gym

**Comment by OrJDev** [comment]
should be fixed in https://github.com/OrJDev/trpc-limiter/commit/9d70e44d0b52a5d9f658fb3b7a0d734f791377f7
please reopen if not.

**Comment by Serpentarius13** [comment]
@OrJDev Hey, thanks for maintaining the lib. I'm having a warning:

```sh
 WARN  Issues with peer dependencies found
.
└─┬ @trpc-limiter/redis 0.0.2
  ├── ✕ unmet peer @trpc/client@next: found 11.0.0-rc.608
  ├── ✕ unmet peer @trpc/server@next: found 11.0.0-rc.608
  └─┬ @trpc-limiter/core 1.0.0
    ├── ✕ unmet peer @trpc/client@next: found 11.0.0-rc.608
    └── ✕ unmet peer @trpc/server@next: found 11.0.0-rc.608

Done in 11.4s
```
with pnpm, is it fixable somehow? I've tried specifying @trpc/server to next in package.json, but no luck
